name: CD Pipeline

on:
  workflow_call:

jobs:
  # Llamada al módulo de publicación (solo si hay un tag)
  publish-pip-package:
   if: startsWith(github.ref, 'refs/tags/')
   permissions:
      contents: read    # Necesario para leer el código
      id-token: write   # El que te está pidiendo el error
   uses: ./.github/workflows/pip-publish.yaml
  publish-github-packages:
    if: startsWith(github.ref, 'refs/tags/')
    uses: ./.github/workflows/github-punlish.yaml
    secrets: inherit
    permissions:
      contents: read
      packages: write # Vital para poder subir el paquete
  deploy-gitub-pages:
    uses: ./.github/workflows/github-page.yaml
    secrets: inherit
    permissions:
      contents: read
      pages: write      # El padre debe habilitar la capacidad de escribir en Pages
      id-token: write
  